export default function Head() {
  return (
    <>
      <title>Search | OpenTables</title>
      <meta content="width=device-width, initial-scale=1" name="v" />
      <meta name="description" content="Generated by create next" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
